spring.application.name=pk-infrastructure
server.port=8081
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
logging.level.org.springframework.security=TRACE
jwt.secret=verySecretKey12345678901234567890
jwt.access-token-expiration-ms=86400000
pki.master.key = ${PKI_MASTER_KEY}