spring.application.name=pk-infrastructure
server.port=8443

server.ssl.enabled=true
server.ssl.key-store=${KEY_STORE_PATH}
server.ssl.key-store-password=${KEY_STORE_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=${KEY_ALIAS}
server.ssl.protocol=TLS
server.ssl.enabled-protocols=TLSv1.2,TLSv1.3

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
logging.level.org.springframework.security=TRACE

# EMAIL CONFIGURATION
spring.mail.host=smtp.gmail.com
spring.mail.port=587
app.mail.from=${MAIL_USERNAME}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true

# JWT
jwt.access-secret=${JWT_SECRET_KEY}
jwt.refresh-secret=${JWT_SECRET_KEY_REFRESH}
pki.keystore.dir=${PKI_KEYSTORE_DIR:keystores}
jwt.access-token-expiration-ms=86400000
jwt.refresh-token-expiration-ms=604800000

pki.master.key = ${PKI_MASTER_KEY}
